name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 20.0.1+9
        distribution: adopt-openj9


    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Run tests
      run: ./gradlew test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Copy folder content recursively to remote
        uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "src/"
          target: "~/prod"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/prod/src/
            sudo docker-compose down && sudo docker-compose up --build -d
